# Configuration file for Weed Detection System

# Camera settings
camera:
  camera_type: "usb"
  resolution: [800, 480]  # Wider resolution to try to get more horizontal view
  framerate: 30  # Increased framerate since camera supports it
  image_path: "images/captured_image.jpg"
  rotation: 0
  brightness: 80  # Significantly increased brightness for low-light conditions
  contrast: 75  # Increased contrast for better visibility
  auto_exposure: true
  hfov: 90.0  # Horizontal field of view in degrees (typical for wide-angle USB camera)
  vfov: 67.5  # Vertical field of view in degrees (typical for wide-angle USB camera)

# AI model settings
ai:
  model_path: "models/weed_detection_v2.pt"
  confidence_threshold: 0.40  # Lowered threshold to detect more objects
  input_size: [320, 240]  # Adjusted input size for better performance
  class_names: ["crop", "weed"]
  enable_debug: true  # Enable debug mode to see detection boxes
  process_every_n_frames: 2  # Process every 2nd frame for more frequent detection
  num_threads: 2  # Reduced threads to prevent overheating
  enable_memory_optimization: true  # Enable memory optimization

# UART communication settings for ESP32
uart:
  device: "/dev/ttyUSB0"  # Change to appropriate port on your system (COM port on Windows)
  baud_rate: 115200  # Matching ESP32 UART configuration
  timeout: 2.0  # Increased timeout for better reliability